DROP TABLE IF EXISTS city CASCADE;
DROP TABLE IF EXISTS district CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS responsible_person CASCADE;
DROP TABLE IF EXISTS shelter CASCADE;
DROP TABLE IF EXISTS shelter_entrance CASCADE;
DROP TABLE IF EXISTS threat CASCADE;
DROP TABLE IF EXISTS shelter_threat CASCADE;
DROP TABLE IF EXISTS feature CASCADE;
DROP TABLE IF EXISTS shelter_feature CASCADE;
DROP TABLE IF EXISTS inventory_item CASCADE;
DROP TABLE IF EXISTS shelter_inventory CASCADE;
DROP TABLE IF EXISTS inspector CASCADE;
DROP TABLE IF EXISTS inspection CASCADE;
DROP TABLE IF EXISTS route CASCADE;
DROP TABLE IF EXISTS route_stop CASCADE;
DROP INDEX IF EXISTS idx_address_location;
DROP EXTENSION IF EXISTS postgis;

DROP USER IF EXISTS sys_admin;
DROP USER IF EXISTS insp_petrenko;
DROP USER IF EXISTS manager_osbb;
DROP USER IF EXISTS public_web_client;

DROP ROLE IF EXISTS admin_role;
DROP ROLE IF EXISTS inspector_role;
DROP ROLE IF EXISTS manager_role;
DROP ROLE IF EXISTS guest_role;
