drop database if exists trolley_depot with (force);
drop role if exists analyst;
drop role if exists mechanic;
drop role if exists dispatcher;
drop user if exists user_analyst;
drop user if exists user_mechanic;
drop user if exists user_dispatcher;

-- Create a new DB
create database trolley_depot
    with
    encoding = 'UTF8'
    connection limit = -1;

\c trolley_depot;

-- Create tables
create table brand (
    name varchar(50) primary key,
    seats integer not null check (seats > 0)
);

create table stop (
    id integer generated by default as identity primary key,
    name varchar(255) not null,
    location varchar(255) not null
);

create table driver (
    id integer primary key,
    name varchar(255) not null
);

create table trolleybus (
    number varchar(20) primary key,
    brand_name varchar(50) not null
);

create table route (
    number varchar(20) primary key,
    start_time TIME not null,
    end_time TIME not null,
    start_point_id integer not null,
    end_point_id integer not null,
    duration_minutes integer not null check (duration_minutes > 0),
    constraint chk_route_time check (end_time > start_time)
);

create table route_stop (
    route_number varchar(20) not null,
    stop_id integer not null,
    stop_order integer not null check (stop_order > 0),
    primary key (route_number, stop_id)
);

create table shift (
    id integer generated by default as identity primary key,
    driver_id integer not null,
    work_date DATE not null,
    start_time TIME not null,
    end_time TIME not null,
    trolleybus_number varchar(20) not null,
    route_number varchar(20) not null,
    constraint chk_shift_time check (end_time > start_time)
);

create table inspection (
    id integer generated by default as identity primary key,
    trolleybus_number varchar(20) not null,
    inspection_date DATE not null default CURRENT_DATE,
    results TEXT, -- null in case of everything is ok
    inspector varchar(255) not null
);

-- Add FKs

ALTER table trolleybus
    ADD constraint fk_trolleybus_brand
        foreign key (brand_name) references brand(name)
        on update cascade on delete restrict;

ALTER table route
    ADD constraint fk_route_start_point
        foreign key (start_point_id) references stop(id)
        on delete restrict,
    ADD constraint fk_route_end_point
        foreign key (end_point_id) references stop(id)
        on delete restrict;

ALTER table route_stop
    ADD constraint fk_route_stop_route
        foreign key (route_number) references route(number)
        on delete cascade,
    ADD constraint fk_route_stop_stop
        foreign key (stop_id) references stop(id)
        on delete cascade;

ALTER table shift
    ADD constraint fk_shift_driver
        foreign key (driver_id) references driver(id)
        on update cascade on delete restrict,
    ADD constraint fk_shift_trolleybus
        foreign key (trolleybus_number) references trolleybus(number)
        on update cascade on delete restrict,
    ADD constraint fk_shift_route
        foreign key (route_number) references route(number)
        on update cascade on delete restrict;

ALTER table inspection
    ADD constraint fk_inspection_trolleybus
        foreign key (trolleybus_number) references trolleybus(number)
        on delete cascade;

-- Create roles

create role analyst;
create role mechanic;
create role dispatcher;

grant connect
    on database trolley_depot
    to analyst, mechanic, dispatcher;
grant usage
    on schema public
    to analyst, mechanic, dispatcher;

grant select
    on all tables in schema public
    to analyst;

alter default privileges
    in schema public
    grant select
        on tables
        to analyst;

grant select
    on trolleybus, brand, inspection
    to mechanic;

grant insert, update
    on inspection
    to mechanic;

grant usage
    on sequence inspection_id_seq
    to mechanic;

grant select
    on all tables in schema public
    to dispatcher;

grant insert, update, delete
    on route, route_stop, shift
    to dispatcher;

grant usage
    on sequence shift_id_seq
    to dispatcher;

-- Create users
create user user_analyst with password '1234';
create user user_mechanic with password '1234';
create user user_dispatcher with password '1234';

grant analyst to user_analyst;
grant mechanic to user_mechanic;
grant dispatcher to user_dispatcher;
